spring.application.name=ex4

spring.datasource.url=jdbc:mysql://localhost:3306/ex4?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=create

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true


server.servlet.session.timeout=5m

admin.username=alon
admin.email=alon39464@gmail.com
admin.password=alon123
